### ISSUE TITLE
LED Light discussion

### ISSUE THREAD

**Issue by vanessasun64** [andydoro/IMA767_MEDP349_Fall2018#1]
This is kinda unrelated to any class assignment, but I have these Christmas lights in my room. I broke two of the bulbs. Usually, with Christmas lights, the lights all go out if one of them stops working. However, even with the broken bulbs, they still keep working on mine. Why?

**Comment by andydoro** [comment]
If the bulbs were all in a simple circuit in series, they would all go out. Fortunately, Christmas light manufacturers put in a bunch of features to keep them working even if a bulb goes out. These include multiple circuits, fuses and shunts. Here's [the clearest explanation I found online](https://www.energy.gov/articles/how-do-holiday-lights-work)
