### ISSUE TITLE
Bluefruit feather M0 poblems

### ISSUE THREAD

**Issue by avertrees** [andydoro/IMA767_MEDP349_Fall2018#10]
I can load code onto the microcontroller and connect to my phone but controlling neopixels has been a challenge. I know that 3.3 volts is not enough power for the strip so I'm wondering if I need to use the Neopxl8 featherwing to control them. 
In the meantime, I'm still looking at ways to control the Arduino from max/msp or processing. looks like processing might be better for the task, but I'm still having trouble finding the correct protocol. The Adafruit guide has a lot of info that I don't quite understand, like ATCommands, GATT, and UART. plz help. I can bring it into class tonight to troubleshoot..

**Comment by andydoro** [comment]
I created a repo for the demo I showed last week https://github.com/andydoro/NeopixelBluefruitDemo 

you could try running this code and seeing if that works.... you're correct that the NeoPixels want 5V while the Feather sends 3.3V signals. You should have a separate power supply for the NeoPixels.
