### ISSUE TITLE
Protoboard vs circuit board vs shield?

### ISSUE THREAD

**Issue by sdaless** [andydoro/IMA767_MEDP349_Fall2018#11]
I'm trying to get together the materials I'll need to solder my project, but I'm coming across a lot of boards and terminology.  I've seen people mentioning protoboards, circuit boards, and shields in online forums and tutorials.  What am I supposed to be using to solder my circuits?

EDIT: Also, when it comes to the placement of the LED matrices I'm looking to use, where would they go in the final product?  I'm trying to avoid using a breadboard but I feel like it isn't very elegant to just have them hanging in space.

**Comment by andydoro** [comment]
circuit boards are just generally any board which has contains the electrical connections for a circuit. These could be (a) professionally "printed" by a PCB (Printed Circuit Board) manufacturer or (b) etched from copper clad. A "shield" is just a PCB designed to sit on top of the Arduino and connect your project to the Arduino. You should be making your permanent circuits on either "perfboard" which is just a fiberglass board with little 0.1" spaced holes with a bit of copper on them, or the newer "perma-protos" from Adafruit which are just PCBs with the same layout as a breadboard. I'd recommend a shield to make easy connections to your Arduino. https://www.adafruit.com/category/358

You could attach the matrix to the shield for something more compact or design them into some kind of enclosure. 

Here's a video: https://www.youtube.com/watch?v=w0c3t0fJhXU
