### ISSUE TITLE
Transporting Projects

### ISSUE THREAD

**Issue by laurastephaniecortes** [andydoro/IMA767_MEDP349_Fall2018#2]
This might seem like a really dumb issue, but is there any recommended way to transport my Arduino and my project back and forth from school? I'm afraid to shove it back into the box and potentially damage it. Does anyone have any suggestions?

**Comment by andydoro** [comment]
This is a good question. I attach a half breadboard and Arduino to a mounting plate- Adafruit sells these: https://www.adafruit.com/product/275

I also then put this into a tupperware container. An Adafruit blog post addresses some of these issues: https://blog.adafruit.com/2012/08/20/transporting-your-projects-backtoschool/

**Comment by sdaless** [comment]
Are we supposed to leave our projects intact?  I assumed there was no way I could safely bring my stuff to and from school, so I just took a lot of pictures and disassembled it.

**Comment by andydoro** [comment]
That's alright- in the future you may have to bring your work in to present it in class. 

Using actual hook-up wire cut to the proper length also helps. 

It also makes sense to get more breadboards to create multiple projects without taking them apart.
