### ISSUE TITLE
piezo buzzer with lights

### ISSUE THREAD

**Issue by avertrees** [andydoro/IMA767_MEDP349_Fall2018#3]
I tried programming the knight rider theme song with the piezo buzzer but I ran into issues independently timing the lights and the buzzer. I think I made a mistake by trying to accomplish both in the loop() function. However, I'm wondering if it would help if I made two functions (one for the lights and one for the buzzer) and called them from the loop() function. Would this work? 

Also, for future reference, is it possible to store and play MIDI files onto an Arduino?

**Comment by andydoro** [comment]
This is a good question!  You might notice that delay() actually stops all activity on the Arduino (although analogWrite() should continue to operate). This is an issue called "blocking." If you want multiple things timed independently, you can create timer functions using a built-in function called millis(). There's an Adafruit tutorial explaining how to do this: https://learn.adafruit.com/multi-tasking-the-arduino-part-1/

**Comment by lilylake1** [comment]
I am unsure of how to find the area where we have issues but i have been
trying to get my home work to work and i keep getting errors and the help
forums are far too complex for me to understand.
