### ISSUE TITLE
CIRC 05 Change LED error 

### ISSUE THREAD

**Issue by lilylake1** [andydoro/IMA767_MEDP349_Fall2018#7]
during the adding of this part in the get to know more of CIRC05 i am getting an error of "changeLED not declared"

https://imgur.com/a/W1sdwqb

...
    int delayTime = 100; // # of ms to delay btween LED updates
for(int i=0; i<8; i++){
  changeLED(i, ON);
  delay(delayTime);
}
for(int i=0;i<8;i++){
  changeLED(i,OFF);
  delay(delayTime);
}
...

**Comment by andydoro** [comment]
`changeLED` is a function declared further down in the code. you need to include the definition of this function further down in the code. I'll go over writing our own functions in class tomorrow.
