### ISSUE TITLE
Correct Battery?

### ISSUE THREAD

**Issue by vanessasun64** [andydoro/IMA767_MEDP349_Fall2018#9]
For my Halloween costume, I’m using the Servo motor. I thought the 9V battery that came in our kits would work well for it, but it stops working after a few seconds and makes jerky movements instead. The only way for the motor to continually work seems to be by keeping the arduino constantly connected to my laptop. Is that the only solution?

**Comment by andydoro** [comment]
9V batteries are not a good choice for motors, they cannot provide enough amperage. You should use a 4xAA battery pack or a LiPo battery. In this case the motor may be drawing too much current and causing the Arduino to reset, so it can be a good idea to use separate battery packs for the motor and the Arduino.

**Comment by vanessasun64** [comment]
How long do you think the 4 AA batteries will last?

**Comment by andydoro** [comment]
"A typical alkaline or NiMH battery in the standard “AA” size has about 2000 to 3000 mAh (or 2 to 3 Ah)." 
"A standard servo will use roughly 100ma idle, (no load) and between 1 and 2 amps in operation, probably averaging around the half amp area (these are just approximations you should really test YOUR servo's with a multimeter"
Using these rough estimates and this [Digikey Battery Life Calculator](https://www.digikey.com/en/resources/conversion-calculators/conversion-calculator-battery-life) I get 10 hours, but that seems generous to me. Definitely bring extra batteries!

**Comment by lilylake1** [comment]
Im also having similar problems. I just bought the same thing we ran into
each other at tinkersphere and my project still doesnt work. is there a way
you can burn out a LED strip ? is that possible from an arduino?

**Comment by andydoro** [comment]
hi Eddy, what type of LED strip is it? are these analog or some kind of Neopixel / Dotstar? can you run some test code to see if you can get the LEDs to light up on their own? a good way to troubleshoot is to see if you're able to get it working with a power supply first before trying batteries, which can be more troublesome.
